# Generated by Django 5.2.14 on 2026-05-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_client_model'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client / Mandant this project belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.client'),
        ),
    ]
