# Generated by Django 5.2.14 on 2026-05-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_client_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planung'), ('active', 'Aktiv'), ('on_hold', 'Pausiert'), ('production', 'Production'), ('done', 'Abgeschlossen'), ('deferred', 'Zurückgestellt'), ('archived', 'Archiviert'), ('end_of_life', 'End of Life')], default='planning', max_length=20),
        ),
    ]
