# Generated by Django 5.2.14 on 2026-05-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, help_text='Hard deadline for this task — shown as milestone in calendar.', null=True),
        ),
    ]
