# Generated by Django 5.2.14 on 2026-05-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_client_model'),
        ('tasks', '0002_add_deadline_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client / Mandant — inherited from project if not set directly.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.client'),
        ),
    ]
