# Generated by Django 5.2.14 on 2026-05-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_add_task_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Story Points (1 SP = 1 Stunde). Schätzung des Aufwands.', max_digits=5, null=True),
        ),
    ]
