# Generated by Django 5.2.14 on 2026-05-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_fix_assignment_xor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'To Do'), ('in_progress', 'In Bearbeitung'), ('waiting', 'Waiting'), ('review', 'Review'), ('done', 'Erledigt')], default='backlog', max_length=20),
        ),
    ]
