# Generated by Django 5.2.14 on 2026-05-16 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_add_checklists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('created', 'erstellt'), ('status_changed', 'Status geändert'), ('assigned', 'zugewiesen'), ('unassigned', 'Zuweisung entfernt'), ('priority_changed', 'Priorität geändert'), ('deadline_changed', 'Deadline geändert'), ('due_date_changed', 'Fälligkeitsdatum geändert'), ('closed', 'abgeschlossen'), ('commented', 'kommentiert'), ('watcher_added', 'Watcher hinzugefügt'), ('watcher_removed', 'Watcher entfernt'), ('project_moved', 'Projekt gewechselt'), ('title_changed', 'Titel geändert'), ('sp_changed', 'Story Points geändert')], max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=500)),
                ('new_value', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Activity',
                'ordering': ['-created_at'],
            },
        ),
    ]
