# Generated by Django 5.2.14 on 2026-05-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_portal_user',
            field=models.BooleanField(default=False, help_text='Portal users have limited access and are not shown in assignee dropdowns'),
        ),
    ]
