# Generated by Django 5.2.14 on 2026-05-13 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_is_portal_user'),
        ('core', '0004_add_capacity_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portal_client',
            field=models.ForeignKey(blank=True, help_text='Client/Mandant assignment for portal users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='core.client'),
        ),
    ]
