# Generated by Django 5.2.14 on 2026-05-12 07:44

from django.db import migrations


def create_initial_data(apps, schema_editor):
    """Create initial Organisation and default teams."""
    Organisation = apps.get_model('core', 'Organisation')
    Team = apps.get_model('teams', 'Team')

    # Create Organisation singleton
    Organisation.objects.get_or_create(
        pk=1,
        defaults={
            'name': 'EOE',
            'slug': 'eoe',
            'description': 'Enterprise Organisation Environment'
        }
    )

    # Create default teams
    Team.objects.get_or_create(
        slug='iun',
        defaults={
            'name': 'IUN',
            'description': 'IUN Team',
            'color': '#6366f1',
            'is_active': True
        }
    )

    Team.objects.get_or_create(
        slug='isartec',
        defaults={
            'name': 'ISARtec',
            'description': 'ISARtec Team',
            'color': '#3b82f6',
            'is_active': True
        }
    )


def reverse_initial_data(apps, schema_editor):
    """Reverse the initial data migration."""
    Team = apps.get_model('teams', 'Team')

    # Delete the default teams (Organisation cannot be deleted due to model's delete method)
    Team.objects.filter(slug__in=['iun', 'isartec']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_initial_data),
    ]
