# Generated by Django 5.2.14 on 2026-05-13 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_client_model'),
        ('teams', '0002_add_is_global_to_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_sp_budget', models.DecimalField(decimal_places=1, help_text='Available Story Points per week for this client/team.', max_digits=6)),
                ('valid_from', models.DateField(help_text='Budget valid from this date (inclusive).')),
                ('valid_until', models.DateField(blank=True, help_text='Budget valid until this date. Null = ongoing.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_budgets', to='core.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_budgets', to='teams.team')),
            ],
            options={
                'verbose_name': 'Capacity Budget',
                'verbose_name_plural': 'Capacity Budgets',
                'ordering': ['client__name', 'team__name', '-valid_from'],
            },
        ),
    ]
