# Generated by Django 5.2.14 on 2026-05-12 07:44

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_provider', models.CharField(default='openai', max_length=20)),
                ('fallback_provider', models.CharField(blank=True, max_length=20)),
                ('monthly_token_budget', models.BigIntegerField(default=10000000)),
                ('per_user_daily_limit', models.IntegerField(default=50000)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI Global Settings',
                'verbose_name_plural': 'AI Global Settings',
            },
        ),
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Anthropic Claude')], max_length=20, unique=True)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField()),
                ('model_name', models.CharField(max_length=100)),
                ('fallback_model', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rpm_limit', models.IntegerField(default=60)),
                ('tpm_limit', models.IntegerField(default=100000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider Config',
                'verbose_name_plural': 'AI Provider Configs',
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='ai_aiusagel_created_7d1979_idx'), models.Index(fields=['user', 'created_at'], name='ai_aiusagel_user_id_e34bca_idx'), models.Index(fields=['team', 'created_at'], name='ai_aiusagel_team_id_2cf10e_idx')],
            },
        ),
    ]
