# Generated by Django 5.2.14 on 2026-05-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Global teams are automatically members of every project and can be assigned tasks without explicit project membership.'),
        ),
    ]
