# Generated by Django 5.2.14 on 2026-05-12 07:59

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph_message_id', models.CharField(max_length=200, unique=True)),
                ('graph_conversation_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=3)),
                ('subject', models.CharField(max_length=500)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('body_preview', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_threads', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Mail Thread',
                'verbose_name_plural': 'Mail Threads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('expires_at', models.DateTimeField()),
                ('scopes', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Mail Token',
                'verbose_name_plural': 'User Mail Tokens',
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_id', models.CharField(max_length=200, unique=True)),
                ('resource', models.CharField(max_length=300)),
                ('expiration', models.DateTimeField()),
                ('client_state', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Subscription',
                'verbose_name_plural': 'Webhook Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
